os: windows
language: sh

install:
  - wget -O opencv.zip https://github.com/opencv/opencv/archive/4.1.2.zip
  - unzip -q opencv.zip
  - cd opencv-4.1.2
  - mkdir -p build
  - cd build
  - >
    cmake ..
    -DBUILD_LIST=core,highgui,videoio,imgcodecs,imgproc,video
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_opencv_world=ON
    -DWITH_WIN32UI=OFF
    -DWITH_DSHOW=OFF
    -DWITH_MSMF=OFF
    -DWITH_DIRECTX=OFF
    -DCMAKE_INSTALL_PREFIX=../../opencv
    -G"Visual Studio 15 2017 Win64"
  - cmake --build . --target INSTALL --config Release
  - cd ../..
  - PATH=`pwd`/opencv/x64/vc15/bin:$PATH

  - choco install python --version 3.7.5
  - PATH=/c/Python37:/c/Python37/Scripts:$PATH

script:
  - echo $PATH
  - python -c "import ctypes; print(ctypes.cdll.LoadLibrary('opencv_world412'))"
